#pragma once

#include <c23pp/lex/lex.h>

extern TOKEN_DECL(TOKEN_EOF);
extern TOKEN_DECL(TOKEN_INVALID);
extern TOKEN_DECL(TOKEN_NEWLINE);
extern TOKEN_DECL(TOKEN_WHITESPACE);
extern TOKEN_DECL(TOKEN_HASH);
extern TOKEN_DECL(TOKEN_LINE_COMMENT_START);
extern TOKEN_DECL(TOKEN_LINE_COMMENT);
extern TOKEN_DECL(TOKEN_BLOCK_COMMENT_OPEN);
extern TOKEN_DECL(TOKEN_BLOCK_COMMENT_CLOSE);
extern TOKEN_DECL(TOKEN_BLOCK_COMMENT);
